[patterns.glider]
rows = 5
cols = 5
pattern = """
.....
.O...
..O..
OOO..
.....
"""

[patterns.blinker]
rows = 5
cols = 5
pattern = """
.....
.....
.OOO.
.....
.....
"""

[patterns.block]
rows = 4
cols = 4
pattern = """
....
.OO.
.OO.
....
"""

[patterns.lightweight_spaceship]
rows = 7
cols = 9
pattern = """
.........
.OO..O...
O.....O..
O......O.
OOOOO....
.........
.........
"""

[patterns.gosper_glider_gun]
rows = 9
cols = 36
pattern = """
.......................................
........................O..............
......................O.O..............
............OO......OO............OO...
...........O...O....OO............OO...
OO........O.....O...OO.................
OO........O...O.OO....O.O..............
..........O.....O.......O..............
...........O...O.......................
............OO........................
"""

[patterns.toad]
rows = 6
cols = 6
pattern = """
......
......
..OOO.
.OOO..
......
......
"""

[patterns.beacon]
rows = 6
cols = 6
pattern = """
......
.OO...
.OO...
...OO.
...OO.
......
"""

[patterns.r_pentomino]
rows = 6
cols = 6
pattern = """
......
..OO..
.OO...
..O...
......
......
"""

[patterns.diehard]
rows = 7
cols = 8
pattern = """
........
......O.
..O.....
.O..OOO.
........
........
........
"""

[patterns.acorn]
rows = 7
cols = 9
pattern = """
.........
.O.......
...O.....
.OO..OOO.
.........
.........
.........
"""

[patterns.beehive]
rows = 5
cols = 6
pattern = """
......
..OO..
.O..O.
..OO..
......
"""

[patterns.loaf]
rows = 6
cols = 6
pattern = """
......
..OO..
.O..O.
..O.O.
...O..
......
"""

[patterns.boat]
rows = 5
cols = 5
pattern = """
.....
.OO..
.O.O.
..O..
.....
"""

[patterns.pulsar]
rows = 17
cols = 17
pattern = """
.................
...OOO...OOO.....
.................
.O....O.O....O...
.O....O.O....O...
.O....O.O....O...
...OOO...OOO.....
.................
...OOO...OOO.....
.O....O.O....O...
.O....O.O....O...
.O....O.O....O...
.................
...OOO...OOO.....
.................
.................
.................
"""
